package org.example.kalkulationsprogramm.service.einkauf;

import com.fasterxml.jackson.databind.ObjectMapper;import jakarta.persistence.EntityManager;import java.math.BigDecimal;import java.util.*;import java.util.stream.Collectors;
import org.example.kalkulationsprogramm.domain.*;import org.example.kalkulationsprogramm.domain.einkauf.*;import org.example.kalkulationsprogramm.dto.Einkauf.EinkaufBestellungDto.Herkunft;import org.example.kalkulationsprogramm.dto.Einkauf.EinkaufLieferungDto.*;import org.example.kalkulationsprogramm.repository.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;

@Service public class EinkaufLieferungService {
 private final EinkaufBestellungRepository orders;private final BestellungRevisionRepository revisions;private final EinkaufLieferungRepository deliveries;private final EinkaufBedarfRepository needs;private final EinkaufMengenService amounts;private final LieferantDokumentRepository documents;private final EntityManager entityManager;private final EinkaufAuditService audit;private final ObjectMapper json;
 public EinkaufLieferungService(EinkaufBestellungRepository orders,BestellungRevisionRepository revisions,EinkaufLieferungRepository deliveries,EinkaufBedarfRepository needs,EinkaufMengenService amounts,LieferantDokumentRepository documents,EntityManager em,EinkaufAuditService audit,ObjectMapper json){this.orders=orders;this.revisions=revisions;this.deliveries=deliveries;this.needs=needs;this.amounts=amounts;this.documents=documents;this.entityManager=em;this.audit=audit;this.json=json;}
 @Transactional public LieferungDto annehmen(Long orderId,Annahme r,Long actor){if(orderId==null||orderId<=0||r==null||r.idempotenzKey()==null||r.version()<0||r.lieferscheinId()==null||r.lieferscheinId()<=0||r.eingang()==null||r.positionen().isEmpty()||actor==null||actor<=0)throw bad("Lieferschein, Eingang, Positionen und Benutzer müssen angegeben sein.");var old=deliveries.findByIdempotenzKey(r.idempotenzKey());if(old.isPresent()){LieferungDto existing=dto(old.get());if(!Objects.equals(existing.bestellungId(),orderId)||!Objects.equals(existing.lieferscheinId(),r.lieferscheinId())||!Objects.equals(existing.eingang(),r.eingang())||!existing.positionen().equals(r.positionen()))throw conflict("Der Idempotenzschlüssel gehört zu einem anderen Lieferscheininhalt.");return existing;}
  EinkaufBestellung order=orders.findeFuerUpdate(orderId).orElseThrow(()->new NoSuchElementException("Bestellung nicht gefunden."));if(order.getVersion()==null||order.getVersion()!=r.version())throw conflict("Die Bestellung wurde geändert; bitte neu laden.");if(order.getStatus()!=BestellungStatus.BESTELLT&&order.getStatus()!=BestellungStatus.TEILGELIEFERT)throw conflict("Nur eine versandte Bestellung kann angenommen werden.");
  LieferantDokument doc=documents.findById(r.lieferscheinId()).orElseThrow(()->new NoSuchElementException("Lieferschein nicht gefunden."));if(doc.getTyp()!=LieferantDokumentTyp.LIEFERSCHEIN||doc.getLieferant()==null||!Objects.equals(doc.getLieferant().getId(),order.getLieferantId()))throw bad("Lieferschein und Bestelllieferant passen nicht zusammen.");
  BestellungRevision revision=latest(orderId);Map<Long,BestellungPosition> lineById=revision.getPositionen().stream().collect(Collectors.toMap(BestellungPosition::getId,x->x));Map<Long,BigDecimal> already=deliveries.findByBestellung_IdOrderByEingangAsc(orderId).stream().flatMap(d->d.getPositionen().stream()).collect(Collectors.groupingBy(p->p.getBestellPosition().getId(),Collectors.reducing(BigDecimal.ZERO,LieferungPosition::getMenge,BigDecimal::add)));
  Map<Long,BigDecimal> deliveredByNeed=new HashMap<>();List<org.example.kalkulationsprogramm.dto.Einkauf.EinkaufPositionDto.Herkunft> booked=new ArrayList<>();Map<Long,BigDecimal> incomingByLine=r.positionen().stream().filter(Objects::nonNull).filter(p->p.bestellPositionId()!=null&&p.menge()!=null).collect(Collectors.groupingBy(Lieferanteil::bestellPositionId,Collectors.mapping(Lieferanteil::menge,Collectors.reducing(BigDecimal.ZERO,BigDecimal::add))));
  for(Lieferanteil part:r.positionen()){if(part==null||part.projektAnteile()==null)throw bad("Lieferscheinposition oder Menge ist ungültig.");BestellungPosition line=lineById.get(part.bestellPositionId());if(line==null||part.menge()==null||part.menge().signum()<=0)throw bad("Lieferscheinposition oder Menge ist ungültig.");BigDecimal previous=already.getOrDefault(line.getId(),BigDecimal.ZERO);if(previous.add(incomingByLine.getOrDefault(line.getId(),BigDecimal.ZERO)).compareTo(line.getMenge())>0)throw conflict("Die Lieferung überschreitet die bestellte Menge.");if(part.charge()==null||part.charge().isBlank())throw bad("Bitte geben Sie die Chargennummer an.");BigDecimal shareTotal=part.projektAnteile().stream().filter(Objects::nonNull).map(Herkunft::menge).filter(Objects::nonNull).reduce(BigDecimal.ZERO,BigDecimal::add);if(shareTotal.compareTo(part.menge())!=0)throw bad("Projektanteile müssen der angenommenen Menge entsprechen.");Set<Long> originIds=line.getHerkuenfte().stream().map(BestellungHerkunft::getBedarfId).collect(Collectors.toSet());for(Herkunft h:part.projektAnteile()){if(h==null||h.bedarfId()==null||h.menge()==null||h.menge().signum()<=0||!originIds.contains(h.bedarfId()))throw bad("Ein Projektanteil gehört nicht zu dieser Bestellposition.");deliveredByNeed.merge(h.bedarfId(),h.menge(),BigDecimal::add);booked.add(new org.example.kalkulationsprogramm.dto.Einkauf.EinkaufPositionDto.Herkunft(h.bedarfId(),h.version(),h.menge()));}}
  booked=booked.stream().collect(Collectors.toMap(org.example.kalkulationsprogramm.dto.Einkauf.EinkaufPositionDto.Herkunft::bedarfId,x->x,(a,b)->new org.example.kalkulationsprogramm.dto.Einkauf.EinkaufPositionDto.Herkunft(a.bedarfId(),a.version(),a.menge().add(b.menge())))).values().stream().toList();
  amounts.buche(booked,EinkaufMengenService.Mengenaktion.LIEFERN,"BESTELLUNG:"+orderId,r.idempotenzKey(),actor);
  EinkaufLieferung delivery=new EinkaufLieferung(order,revision.getId(),doc.getId(),r.eingang(),r.idempotenzKey(),actor);
  for(Lieferanteil p:r.positionen()){BestellungPosition line=lineById.get(p.bestellPositionId());delivery.addPosition(new LieferungPosition(delivery,line,p.menge(),p.charge(),p.schmelznummer(),p.projektAnteile().stream().map(x->map(x)).toList()));}
  deliveries.saveAndFlush(delivery);delivery.getPositionen().forEach(p->{if(p.getCharge()!=null&&!p.getCharge().isBlank())entityManager.persist(new EinkaufCharge(p,p.getCharge(),p.getSchmelznummer()));});doc.setEinkaufBestellungId(orderId);boolean complete=revision.getPositionen().stream().allMatch(line->already.getOrDefault(line.getId(),BigDecimal.ZERO).add(r.positionen().stream().filter(p->Objects.equals(p.bestellPositionId(),line.getId())).map(Lieferanteil::menge).reduce(BigDecimal.ZERO,BigDecimal::add)).compareTo(line.getMenge())>=0);order.setStatus(complete?BestellungStatus.GELIEFERT:BestellungStatus.TEILGELIEFERT);needs.flush();Map<Long,EinkaufBedarf> latestNeeds=needs.findeAlleFuerUpdate(booked.stream().map(org.example.kalkulationsprogramm.dto.Einkauf.EinkaufPositionDto.Herkunft::bedarfId).toList()).stream().collect(Collectors.toMap(EinkaufBedarf::getId,x->x));revision.getPositionen().forEach(line->line.getHerkuenfte().forEach(h->{if(latestNeeds.containsKey(h.getBedarfId()))h.setBedarfVersion(latestNeeds.get(h.getBedarfId()).getVersion());}));audit.protokolliere("BESTELLUNG",orderId,"LIEFERUNG_ANGENOMMEN",actor,null,json.valueToTree(dto(delivery)),"Lieferschein "+doc.getId());return dto(delivery);}
 @Transactional public BestaetigungDto bestaetigungErfassen(Long orderId,Bestaetigung r,Long actor){if(orderId==null||orderId<=0||r==null||r.dokumentId()==null||r.datum()==null||actor==null||actor<=0)throw bad("Auftragsbestätigung und Datum fehlen.");EinkaufBestellung order=orders.findeFuerUpdate(orderId).orElseThrow(()->new NoSuchElementException("Bestellung nicht gefunden."));LieferantDokument doc=documents.findById(r.dokumentId()).orElseThrow(()->new NoSuchElementException("Bestätigung nicht gefunden."));if(doc.getTyp()!=LieferantDokumentTyp.AUFTRAGSBESTAETIGUNG||doc.getLieferant()==null||!Objects.equals(doc.getLieferant().getId(),order.getLieferantId()))throw bad("Auftragsbestätigung und Lieferant passen nicht zusammen.");BestellungRevision current=latest(orderId);Map<Long,BestellungPosition> lines=current.getPositionen().stream().collect(Collectors.toMap(BestellungPosition::getId,x->x));List<Map<String,Object>> snapshot=new ArrayList<>();boolean deviation=false;Set<Long> seen=new HashSet<>();for(BestaetigtePosition p:r.positionen()){BestellungPosition line=lines.get(p.bestellPositionId());if(line==null||!seen.add(p.bestellPositionId()))throw bad("Eine bestätigte Position ist nicht Teil dieser Bestellung.");boolean diff=p.menge()==null||p.menge().compareTo(line.getMenge())!=0||p.nettoPreis()!=null&&line.getNettoEinzelpreis()!=null&&p.nettoPreis().compareTo(line.getNettoEinzelpreis())!=0||p.abweichung()!=null&&!p.abweichung().isBlank();deviation|=diff;snapshot.add(map(p));}if(seen.size()!=lines.size())deviation=true;BestellBestaetigung confirmation=new BestellBestaetigung(order,doc.getId(),r.datum(),r.liefertermin(),snapshot,deviation,actor);entityManager.persist(confirmation);doc.setEinkaufBestellungId(orderId);order.setLieferantenStatus(deviation?LieferantenBestellstatus.ABWEICHUNG:LieferantenBestellstatus.BESTAETIGT);audit.protokolliere("BESTELLUNG",orderId,"AUFTRAGSBESTAETIGUNG_ERFASST",actor,null,json.valueToTree(snapshot),deviation?"Abweichungen zur Prüfung":"Werte separat gespeichert");return new BestaetigungDto(confirmation.getId(),doc.getId(),r.datum(),r.liefertermin(),deviation,r.positionen());}
 private BestellungRevision latest(Long id){return revisions.findFirstByBestellung_IdOrderByNummerDesc(id).orElseThrow(()->conflict("Bestellung hat keine Fassung."));}
 private Map<String,Object> map(Object value){return json.convertValue(value,Map.class);}private LieferungDto dto(EinkaufLieferung d){List<Lieferanteil> parts=d.getPositionen().stream().map(p->new Lieferanteil(p.getBestellPosition().getId(),p.getMenge(),p.getCharge(),p.getSchmelznummer(),p.getProjektAnteile().stream().map(x->json.convertValue(x,Herkunft.class)).toList())).toList();return new LieferungDto(d.getId(),d.getBestellung().getId(),d.getRevisionId(),d.getLieferscheinId(),d.getEingang(),parts);}
 private static ResponseStatusException bad(String s){return new ResponseStatusException(HttpStatus.BAD_REQUEST,s);}private static ResponseStatusException conflict(String s){return new ResponseStatusException(HttpStatus.CONFLICT,s);}
}
