import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button } from '../../../components/ui/button';
import { VersandVorschauDialog, type VersandVorschau } from './VersandVorschauDialog';

type Snapshot = { lieferantId: number; kontaktId: number; lieferantenname: string; email: string; name: string | null; anrede: string | null; eigeneKundennummer: string | null };
type Beteiligung = { id: number; lieferantenname: string; status: string; version: number; kontakt?: Snapshot };
type Versand = { beteiligungId: number; versand: { id: number; version: number; status: 'VORBEREITET'|'LAEUFT'|'ANGENOMMEN'|'FEHLGESCHLAGEN'|'UNKLAR'; fehlerCode?: string | null; messageId?: string | null } };
export function AnfrageLieferanten({ anfrageId, revisionId, lieferanten, historisch = false }: { anfrageId: number; revisionId: number; lieferanten: Beteiligung[]; historisch?: boolean }) {
 const [ausgewaehlt, setAusgewaehlt] = useState<number | null>(null); const [vorschau, setVorschau] = useState<VersandVorschau | null>(null); const [fehler, setFehler] = useState(''); const [versandstatus, setVersandstatus] = useState<Versand[]>([]);
 const versandLaden = useCallback(async () => { try { const r = await fetch(`/api/einkauf/anfragen/${anfrageId}/revisionen/${revisionId}/versandstatus`); if (!r.ok) throw new Error('Versandstatus konnte nicht geladen werden.'); const data = await r.json() as Versand[]; setVersandstatus(data); } catch (e) { setFehler(e instanceof Error ? e.message : 'Versandstatus konnte nicht geladen werden.'); } }, [anfrageId, revisionId]);
 useEffect(() => { void versandLaden(); }, [versandLaden]);
 const aktiveVersandjobs = useMemo(() => versandstatus.some(v => v.versand.status === 'VORBEREITET' || v.versand.status === 'LAEUFT'), [versandstatus]);
 useEffect(() => { if (!aktiveVersandjobs) return; const timer = window.setInterval(() => { void versandLaden(); }, 2000); return () => window.clearInterval(timer); }, [aktiveVersandjobs, versandLaden]);
 const ladeVorschau = async (l: Beteiligung) => { setFehler(''); try { const templates = await fetch('/api/email-textvorlagen'); if (!templates.ok) throw new Error('Einkaufsvorlagen konnten nicht geladen werden.'); const alle = await templates.json() as { id: number; dokumentTyp: string; standard?: boolean; aktiv?: boolean }[]; const template = alle.find(t => t.dokumentTyp === 'EINKAUF_ANFRAGE' && t.aktiv !== false && t.standard) ?? alle.find(t => t.dokumentTyp === 'EINKAUF_ANFRAGE' && t.aktiv !== false); if (!template) throw new Error('Bitte zuerst eine aktive Vorlage für Einkaufsanfragen anlegen.'); const r = await fetch(`/api/einkauf/anfragen/${anfrageId}/lieferanten/${l.id}/vorschau?templateId=${template.id}`); const d = await r.json(); if (!r.ok) throw new Error(d.message || 'Versandvorschau konnte nicht geladen werden.'); setVorschau(d); setAusgewaehlt(l.id); } catch (e) { setFehler(e instanceof Error ? e.message : 'Versandvorschau konnte nicht geladen werden.'); } };
 const freigeben = async (hash: string) => { if (!vorschau || ausgewaehlt === null) return; const r = await fetch(`/api/einkauf/anfragen/${anfrageId}/lieferanten/${ausgewaehlt}/senden`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ version: vorschau.version, vorschauHash: hash, idempotenzKey: crypto.randomUUID() }) }); if (!r.ok) { const d = await r.json().catch(() => ({})); throw new Error(d.message || 'Anfrage konnte nicht versendet werden.'); } setVorschau(null); await versandLaden(); };
 const erneutSenden = async (v: Versand) => { setFehler(''); try { const r = await fetch(`/api/einkauf/anfragen/${anfrageId}/lieferanten/${v.beteiligungId}/versand/${v.versand.id}/erneut`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ version: v.versand.version }) }); if (!r.ok) { const d = await r.json().catch(() => ({})); throw new Error(d.message || 'Fehlgeschlagener Versand konnte nicht wiederholt werden.'); } await versandLaden(); } catch (e) { setFehler(e instanceof Error ? e.message : 'Fehlgeschlagener Versand konnte nicht wiederholt werden.'); } };
 const jobFuer = (id: number) => versandstatus.find(v => v.beteiligungId === id)?.versand;
 return <section className="rounded-lg border border-slate-200 bg-white p-4"><h2 className="font-semibold">Lieferanten und Versand</h2>{fehler && <p role="alert" className="my-2 text-sm text-rose-700">{fehler}</p>}<ul className="divide-y divide-slate-100">{lieferanten.map(l => {const job=jobFuer(l.id);const darfSenden=!historisch&&l.status==='AUSSTEHEND'&&!job;return <li key={l.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-medium">{l.lieferantenname}</p>{l.kontakt&&<p className="text-sm text-slate-600">{l.kontakt.name||'Einkauf'} · {l.kontakt.email}</p>}<p className="text-sm text-slate-600">{l.status} · Revision {revisionId}{job?` · Versand ${job.status}`:''}</p>{job?.fehlerCode&&<p className="text-sm text-rose-700">Versandfehler: {job.fehlerCode}</p>}{job?.messageId&&<p className="text-xs text-slate-500">Nachrichtenkennung: {job.messageId}</p>}</div>{!historisch&&<div className="flex gap-2">{darfSenden&&<Button size="sm" onClick={()=>void ladeVorschau(l)}>Vorschau und Freigabe</Button>}{job?.status==='FEHLGESCHLAGEN'&&<Button size="sm" variant="outline" onClick={()=>void erneutSenden({beteiligungId:l.id,versand:job})}>Sicher fehlgeschlagen · erneut senden</Button>}</div>}</li>;})}</ul>{vorschau && <VersandVorschauDialog vorschau={vorschau} onFreigeben={freigeben} onSchliessen={() => setVorschau(null)} />}</section>;
}
