import { useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, ChevronDown, FileText, Gem } from 'lucide-react';
import { Button } from '../../../components/ui/button';
import { useToast } from '../../../components/ui/toast';
import { einkaufApi } from '../api';
import type { AngebotVersion } from '../types';
import type { Vergleich, AngebotVersionMitPositionsIds } from '../angebotsTypes';
import type { AnfrageAngeboteEintrag } from '../angebotsTypes';

interface VergleichsAnfragePosition { id: number; anfragePositionId: number; originalNummer: string | null; originalText: string | null; art: string | null; artikelId: number | null; werkstoff: string | null; abmessung: string | null; einheit: string | null; menge: number | null }
interface PreisUebernahmeQuelle { angebotVersionId: number; angebotPositionId: number; artikelId: number; lieferantId: number; preis: number; waehrung: string; einheit: string; gueltigBis: string | null }
interface VergleichsAnbieter { lieferantId: number; beteiligungId: number; lieferantenname: string; version: AngebotVersionMitPositionsIds; summe: Vergleich['angebote'][number] | undefined }
const formatEuro = (value: number | null | undefined) => value == null ? 'offen' : `${value.toLocaleString('de-DE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} €`;
const formatPreis = (value: number | null | undefined, unit: string | null | undefined) => value == null ? 'offen' : `${value.toLocaleString('de-DE', { maximumFractionDigits: 4 })} ${unit?.toLowerCase() ?? ''}`;

export function Angebotsvergleich({ anfrageId, onBestellung, onBearbeiten, onPreisUebernehmen, revisionId, historisch = false, reloadToken = 0, onSaved }: { anfrageId: number; onBestellung: (angebotVersionId: number, bestaetigtAbgelaufen?: boolean) => void | Promise<void>; onBearbeiten?: (angebot: { beteiligungId: number; angebotId: number; version: AngebotVersion }) => void; onPreisUebernehmen?: (quelle: PreisUebernahmeQuelle) => void; revisionId?: number; historisch?: boolean; reloadToken?: number; onSaved?: () => void }) {
  const toast = useToast(); const [anbieter, setAnbieter] = useState<VergleichsAnbieter[]>([]); const [positionen, setPositionen] = useState<VergleichsAnfragePosition[]>([]);
  const [vergleich, setVergleich] = useState<Vergleich | null>(null); const [bestellWartet, setBestellWartet] = useState<number | null>(null); const [laden, setLaden] = useState(true); const [fehler, setFehler] = useState(''); const [ansichtHistorisch, setAnsichtHistorisch] = useState(false);
  const [ablaufBestaetigt, setAblaufBestaetigt] = useState<number[]>([]); const [abweichungsgrund, setAbweichungsgrund] = useState<Record<number, string>>({});
  useEffect(() => {
    let aktiv = true;
    Promise.resolve().then(() => {
      if (aktiv) { setLaden(true); setFehler(''); }
      return Promise.all([
      einkaufApi.get<{ angezeigteRevisionId: number; historisch: boolean; positionen: Array<{ id: number; snapshot: { art?: string | null; artikelId?: number | null; interneReferenz: string | null; bezeichnung: string | null; werkstoff?: string | null; abmessung?: string | null; basis?: { einheit: string | null; menge: number | null } | null }; herkuenfte: Array<{ bedarfId: number; version: number; menge: number }> }> }>(`/api/einkauf/anfragen/${anfrageId}${historisch && revisionId ? `/revisionen/${revisionId}` : ''}`),
      einkaufApi.get<AnfrageAngeboteEintrag[]>(`/api/einkauf/anfragen/${anfrageId}/angebote`),
      einkaufApi.get<Vergleich>(`/api/einkauf/anfragen/${anfrageId}/vergleich`),
      ]);
    }).then(([anfrage, offers, ranked]) => {
      if (!aktiv) return;
      const effectiveRevision = revisionId ?? anfrage.angezeigteRevisionId;
      setAnsichtHistorisch(historisch || anfrage.historisch);
      const currentOffers = offers.map(item => ({ ...item, version: item.angebot.versionen.filter(v => v.anfrageRevisionId === effectiveRevision).sort((a, b) => a.nummer - b.nummer).at(-1) })).filter((item): item is AnfrageAngeboteEintrag & { version: AngebotVersion } => !!item.version);
      setAnbieter(currentOffers.map(item => ({ lieferantId: item.lieferantId, beteiligungId: item.angebot.beteiligungId, lieferantenname: item.lieferantenname, version: item.version as AngebotVersionMitPositionsIds,
        summe: ranked.angebote.find(row => row.angebotVersionId === item.version.id) })));
      setPositionen(anfrage.positionen.map(p => ({ id: p.id, anfragePositionId: p.id, originalNummer: p.snapshot.interneReferenz, originalText: p.snapshot.bezeichnung, art: p.snapshot.art ?? null, artikelId: p.snapshot.artikelId ?? null, werkstoff: p.snapshot.werkstoff ?? null, abmessung: p.snapshot.abmessung ?? null, einheit: p.snapshot.basis?.einheit ?? null, menge: p.snapshot.basis?.menge ?? null })));
      setVergleich(ranked);
    }).catch(error => { if (aktiv) { const message = error instanceof Error ? error.message : 'Angebotsvergleich konnte nicht geladen werden.'; setFehler(message); toast.error(message); } })
      .finally(() => { if (aktiv) setLaden(false); });
    return () => { aktiv = false; };
  }, [anfrageId, revisionId, historisch, reloadToken, toast]);

  const freigeben = async (item: VergleichsAnbieter) => {
    try { await einkaufApi.post(`/api/einkauf/angebote/${item.version.angebotId}/bestaetigen?version=${item.version.version}`, {}); toast.success('Angebotsfassung wurde als geprüft bestätigt.'); onSaved?.(); }
    catch (error) { toast.error(error instanceof Error ? error.message : 'Angebot konnte nicht bestätigt werden.'); }
  };
  const abweichungBestaetigen = async (item: VergleichsAnbieter) => {
    const grund = abweichungsgrund[item.version.id]?.trim(); if (!grund) { toast.error('Bitte begründen Sie die Abweichungsfreigabe.'); return; }
    try { await einkaufApi.post(`/api/einkauf/angebote/${item.version.angebotId}/abweichung-bestaetigen?version=${item.version.version}`, { begruendung: grund }); toast.success('Technische Abweichung wurde ausdrücklich freigegeben.'); onSaved?.(); }
    catch (error) { toast.error(error instanceof Error ? error.message : 'Abweichung konnte nicht bestätigt werden.'); }
  };
  if (laden) return <section className="rounded-lg border border-slate-200 bg-white p-4" role="status">Angebote werden verglichen …</section>;
  return <section aria-labelledby="angebotsvergleich-titel" className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm">
    <div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-wide text-rose-600">Einkauf</p><h2 id="angebotsvergleich-titel" className="text-xl font-semibold text-slate-900">Angebotsvergleich</h2><p className="text-sm text-slate-600">Vollkosten und technische Eignung nach Lieferant vergleichen.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-sm text-slate-700">{anbieter.length} Angebote</span></div>
    {fehler && <p role="alert" className="text-sm text-rose-700">{fehler}</p>}
    {(historisch || ansichtHistorisch) && <p className="mb-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Frühere Anfragefassung – Angebote und Vergleich können sich auf einen anderen aktuellen Stand beziehen. Keine Bestellung aus dieser Ansicht vorbereiten.</p>}
    {anbieter.length === 0 ? <p className="rounded-lg border border-dashed border-slate-300 p-5 text-center text-sm text-slate-600">Zu dieser Anfragefassung liegen noch keine Angebote vor.</p> : <>
      <div className="overflow-x-auto rounded-lg border border-slate-200"><table className="min-w-[760px] border-collapse text-left text-sm"><thead className="bg-slate-50"><tr><th className="sticky left-0 z-10 min-w-52 bg-slate-50 p-3">Anfrageposition</th>{anbieter.map(item => <th key={item.version.id} className="min-w-56 border-l border-slate-200 p-3 align-top"><p className="font-semibold">{item.lieferantenname}</p><p className="mt-1 text-xs text-slate-500">Angebot {item.version.angebotsnummer ?? `#${item.version.nummer}`} · Fassung {item.version.nummer}</p></th>)}</tr></thead>
        <tbody>{positionen.map((position, index) => <tr key={`${position.anfragePositionId}-${index}`} className="border-t border-slate-200"><th className="sticky left-0 bg-white p-3 align-top font-medium"><span className="block">{position.originalNummer ?? `Position ${index + 1}`}</span><span className="block text-xs font-normal text-slate-600">{position.originalText ?? 'Keine Bezeichnung'}</span></th>{anbieter.map(item => { const offered = item.version.positionen.find(p => p.anfragePositionId === position.anfragePositionId); const material = offered?.kosten.find(cost => cost.art === 'MATERIAL' && cost.betrag != null); const validPrice = material?.betrag; return <td key={item.version.id} className="border-l border-slate-200 p-3 align-top">{offered?.angeboten ? <><p className="font-medium">{formatPreis(offered.angeboten.menge, offered.angeboten.einheit)}</p>{offered.abweichungen.map((text, ix) => <p key={ix} className="mt-1 text-xs text-amber-800"><AlertTriangle className="mr-1 inline h-3 w-3" />{text}</p>)}{offered.zeugnisse.filter(z => z.status !== 'LIEFERBAR' && z.status !== 'BESTAETIGT').map((z, ix) => <p key={ix} className="mt-1 text-xs text-amber-800">{z.art.replaceAll('_', ' ')} · {z.status.toLowerCase()}</p>)}{onPreisUebernehmen && !historisch && !ansichtHistorisch && position.art === 'ARTIKEL' && position.artikelId != null && offered.id != null && validPrice != null && item.version.waehrung != null && item.version.status === 'GEPRUEFT' && (offered.abweichungen.length === 0 || item.version.abweichungBestaetigtVon != null) && <Button size="sm" variant="outline" className="mt-2" onClick={() => onPreisUebernehmen({ angebotVersionId: item.version.id, angebotPositionId: offered.id!, artikelId: position.artikelId!, lieferantId: item.lieferantId, preis: validPrice, waehrung: item.version.waehrung!, einheit: material?.basis ?? offered.angeboten?.einheit ?? 'STUECK', gueltigBis: item.version.gueltigBis })}>Preis übernehmen · {position.originalNummer ?? index + 1}</Button>}</> : <span className="text-slate-500">offen</span>}</td>; })}</tr>)}
          <tr className="border-t-2 border-slate-300 bg-slate-50"><th className="sticky left-0 bg-slate-50 p-3 font-semibold">Vollkosten netto</th>{anbieter.map(item => <td key={item.version.id} className="border-l border-slate-200 p-3 align-top"><p className="text-base font-semibold">{formatEuro(item.summe?.nettoGesamt)}</p>{vergleich?.bestesAngebotVersionId === item.version.id && <span className="text-xs text-slate-500">Empfohlen</span>}{item.summe?.hindernisse.map((why, ix) => <p key={ix} className="mt-1 text-xs text-amber-800">{why}</p>)}{item.version.skontoProzent != null && <p className="mt-1 text-xs text-slate-600">Skonto {item.version.skontoProzent}% · nur Hinweis, nicht abgezogen</p>}</td>)}</tr>
        </tbody></table></div>
      <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{anbieter.map(item => { const s = item.summe; const expiredOnly = !!s?.vollstaendig && !!s.technischGeeignet && s.nettoGesamt != null && !s.gueltig && s.hindernisse.length > 0 && s.hindernisse.every(reason => reason.toLocaleLowerCase('de-DE').includes('abgelauf')); const expiredConfirmed = ablaufBestaetigt.includes(item.version.id); const eligible = !(historisch || ansichtHistorisch) && item.version.status === 'GEPRUEFT' && !!s?.vollstaendig && !!s.technischGeeignet && (s.gueltig || (expiredOnly && expiredConfirmed)) && s.nettoGesamt != null && !(item.version.positionen.some(p => p.abweichungen.length > 0) && item.version.abweichungBestaetigtVon == null); const recommended = vergleich?.bestesAngebotVersionId === item.version.id;
          return <article key={item.version.id} className={`rounded-lg border p-4 ${recommended ? 'border-rose-300 bg-rose-50/40' : 'border-slate-200'}`}><div className="flex items-start justify-between gap-2"><div><h3 className="font-semibold">{item.lieferantenname}</h3><p className="mt-1 text-lg font-semibold">{formatEuro(s?.nettoGesamt)}</p></div>{recommended ? <span className="inline-flex items-center gap-1 text-xs font-medium text-rose-700"><CheckCircle2 className="h-4 w-4" />Günstigstes geeignetes Angebot</span> : s?.technischGeeignet ? <span className="text-xs text-slate-600">Vergleichbar</span> : null}</div>
            <details className="mt-3"><summary className="flex cursor-pointer list-none items-center gap-1 text-sm text-rose-700"><ChevronDown className="h-4 w-4" />Rechenweg und Quellen</summary><ul className="mt-2 space-y-2 text-xs text-slate-700">{s?.rechnung.map((step, index) => <li key={`${step.key}-${index}`}><span className="font-medium">{step.key}:</span> {step.formel} = {formatEuro(step.ergebnis)} · {step.quellenbezug}</li>)}{!s?.rechnung.length && <li>Für dieses Angebot liegen keine vollständigen Rechenschritte vor.</li>}</ul></details>
            {item.version.originalDateiId && <p className="mt-2 text-xs text-slate-500"><FileText className="mr-1 inline h-3 w-3" />Originalangebot liegt vor.</p>}
            {item.version.status !== 'GEPRUEFT' && <Button variant="outline" size="sm" className="mt-3 w-full" onClick={() => void freigeben(item)}>Ich habe Angebot und Preise geprüft</Button>}
            {item.version.positionen.some(p => p.abweichungen.length > 0) && item.version.abweichungBestaetigtVon == null && <div className="mt-3 space-y-2"><label className="block text-sm">Begründung für technische Abweichung<input className="mt-1 w-full rounded border border-slate-300 px-2 py-1" value={abweichungsgrund[item.version.id] ?? ''} onChange={event => setAbweichungsgrund(current => ({ ...current, [item.version.id]: event.target.value }))} /></label><Button variant="outline" size="sm" className="w-full" onClick={() => void abweichungBestaetigen(item)}>Abweichung ausdrücklich freigeben</Button></div>}
            {onBearbeiten && <Button variant="outline" className="mt-3 w-full" size="sm" onClick={() => onBearbeiten({ beteiligungId: item.beteiligungId, angebotId: item.version.angebotId, version: item.version })}>Angebot bearbeiten</Button>}
            {expiredOnly && <label className="mt-3 flex items-start gap-2 text-sm text-amber-900"><input className="mt-1" type="checkbox" checked={expiredConfirmed} onChange={event => setAblaufBestaetigt(current => event.target.checked ? [...current, item.version.id] : current.filter(id => id !== item.version.id))} />Abgelaufenen Preis ausdrücklich für diese Bestellung bestätigen.</label>}
            <Button className="mt-4 w-full" size="sm" disabled={!eligible || bestellWartet != null} title={!eligible ? s?.hindernisse.join(' · ') || 'Angebot muss vollständig, technisch geeignet und gültig sein.' : undefined} onClick={() => { setBestellWartet(item.version.id); Promise.resolve(onBestellung(item.version.id, expiredOnly && expiredConfirmed)).finally(() => setBestellWartet(null)); }}><Gem className="mr-2 h-4 w-4" />{bestellWartet === item.version.id ? 'Entwurf wird erstellt …' : 'Als Bestellung vorbereiten'} · Fassung {item.version.nummer}</Button>
          </article>; })}</div>
    </>}
  </section>;
}
