import { useEffect, useMemo, useState } from 'react';
import { LieferantSearchModal, type LieferantSuchErgebnis } from '../../../components/LieferantSearchModal';
import { Button } from '../../../components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../../../components/ui/dialog';
import { DatePicker } from '../../../components/ui/datepicker';
import { Select } from '../../../components/ui/select-custom';
import { useToast } from '../../../components/ui/toast';
import { validateDecimalInput } from '../../../lib/numberInput';
import { einkaufApi } from '../api';
import type { BedarfResponse, KontaktSnapshot, Einheit } from '../types';

interface Kontakt { id: number; version: number; name: string | null; anrede: string | null; email: string; standardBestellung: boolean; aktiv: boolean }
interface Lieferant extends LieferantSuchErgebnis { eigeneKundennummer?: string | null }
interface Draft { menge: string; preis: string; bestaetigtAm: string; gueltigBis: string; quelle: string }
const heute = () => new Date().toLocaleDateString('sv-SE');
const draft = (need: BedarfResponse): Draft => ({ menge: String(need.mengen.disponierbar ?? '').replace('.', ','), preis: '', bestaetigtAm: '', gueltigBis: '', quelle: '' });

export function DirektbestellungDialog({ onClose, onCreated }: { onClose: () => void; onCreated: (bestellungId: number) => void }) {
  const toast = useToast(); const [bedarfe, setBedarfe] = useState<BedarfResponse[]>([]); const [selected, setSelected] = useState<number[]>([]); const [drafts, setDrafts] = useState<Record<number, Draft>>({}); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [picker, setPicker] = useState(false); const [lieferant, setLieferant] = useState<Lieferant | null>(null); const [kontakte, setKontakte] = useState<Kontakt[]>([]); const [kontaktId, setKontaktId] = useState(''); const [liefertermin, setLiefertermin] = useState(''); const [bestaetigungsfrist, setBestaetigungsfrist] = useState(''); const [bedingungen, setBedingungen] = useState('');
  useEffect(() => { let aktiv = true; einkaufApi.get<{ content: BedarfResponse[] }>('/api/einkauf/bedarf?page=0&size=100').then(page => { if (aktiv) { const eligible = page.content.filter(need => need.position?.artikelId != null && (need.mengen?.disponierbar ?? 0) > 0); setBedarfe(eligible); setDrafts(Object.fromEntries(eligible.map(need => [need.id, draft(need)]))); } }).catch(error => { if (aktiv) toast.error(error instanceof Error ? error.message : 'Bedarfe konnten nicht geladen werden.'); }).finally(() => { if (aktiv) setLoading(false); }); return () => { aktiv = false; }; }, [toast]);
  const kontakt = useMemo(() => kontakte.find(item => String(item.id) === kontaktId), [kontakte, kontaktId]);
  const chooseSupplier = async (value: LieferantSuchErgebnis) => { setPicker(false); try { const [detail, rows] = await Promise.all([einkaufApi.get<Lieferant>(`/api/lieferanten/${value.id}`), einkaufApi.get<Kontakt[]>(`/api/einkauf-kontakte?lieferantId=${value.id}`)]); setLieferant({ ...value, ...detail }); const active = rows.filter(item => item.aktiv); setKontakte(active); setKontaktId(String(active.find(item => item.standardBestellung)?.id ?? active[0]?.id ?? '')); if (!active.length) toast.error('Für diesen Lieferanten ist kein aktiver Bestellkontakt hinterlegt.'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Lieferantenkontakt konnte nicht geladen werden.'); } };
  const update = (id: number, key: keyof Draft, value: string) => setDrafts(current => ({ ...current, [id]: { ...current[id], [key]: value } }));
  const create = async () => {
    if (!lieferant || !kontakt) { toast.error('Bitte Lieferant und Bestellkontakt auswählen.'); return; }
    if (!selected.length) { toast.error('Bitte mindestens einen verfügbaren Bedarf auswählen.'); return; }
    const paket = []; const preise = [];
    for (const id of selected) {
      const need = bedarfe.find(item => item.id === id)!; const values = drafts[id];
      const qty = validateDecimalInput(values.menge, { label: `Menge ${need.position.interneReferenz ?? id}`, required: true, min: 0 });
      if (!qty.valid) { toast.error(qty.message); return; } if (qty.value == null || qty.value > (need.mengen.disponierbar ?? 0)) { toast.error(`Menge ${need.position.interneReferenz ?? id} darf den noch verfügbaren Bedarf nicht überschreiten.`); return; }
      const price = validateDecimalInput(values.preis, { label: `Preis ${need.position.interneReferenz ?? id}`, required: true, min: 0 });
      if (!price.valid) { toast.error(price.message); return; } if (price.value == null || price.value <= 0) { toast.error('Der bestätigte Preis muss größer als 0 sein.'); return; }
      if (!values.bestaetigtAm || values.bestaetigtAm > heute()) { toast.error('Bitte ein gültiges, nicht zukünftiges Bestätigungsdatum angeben.'); return; }
      if (values.gueltigBis && values.gueltigBis < heute()) { toast.error('Dieser Preis ist abgelaufen. Erstellen Sie eine Anfrage und holen Sie ein aktuelles Angebot ein.'); return; }
      if (!values.quelle.trim()) { toast.error('Bitte Quelle oder Belegreferenz je Preis angeben.'); return; }
      if (!need.position.basis?.einheit) { toast.error('Für diesen Bedarf fehlt eine eindeutige Preiseinheit.'); return; }
      paket.push({ bedarfId: id, version: need.version, menge: qty.value });
      preise.push({ bedarfId: id, preis: price.value, einheit: need.position.basis.einheit as Einheit, basisMenge: 1, preisHistorieId: null, bestaetigtAm: values.bestaetigtAm, gueltigBis: values.gueltigBis || null, bestaetigungsbeleg: values.quelle.trim() });
    }
    const empfaenger: KontaktSnapshot = { lieferantId: lieferant.id, kontaktId: kontakt.id, lieferantenname: lieferant.lieferantenname, email: kontakt.email, name: kontakt.name, anrede: kontakt.anrede, eigeneKundennummer: lieferant.eigeneKundennummer ?? null };
    setBusy(true); try { const result = await einkaufApi.post<{ id: number }>('/api/einkauf/bestellungen/direkt', { lieferantId: lieferant.id, empfaenger, paket, preise, liefertermin: liefertermin || null, bestaetigungsfrist: bestaetigungsfrist || null, bedingungen: bedingungen.trim() || null, idempotenzKey: crypto.randomUUID() }); toast.success('Direktbestellentwurf wurde angelegt; Mengen sind zunächst nur reserviert.'); onCreated(result.id); }
    catch (error) { toast.error(error instanceof Error ? error.message : 'Direktbestellung konnte nicht angelegt werden.'); } finally { setBusy(false); }
  };
  return <Dialog open onOpenChange={open => { if (!open) onClose(); }} className="w-[min(64rem,calc(100vw-2rem))]"><DialogHeader className="px-6 pt-6"><DialogTitle>Direktbestellung vorbereiten</DialogTitle><DialogDescription>Für jeden Bedarf ist ein belegter, bestätigter und noch gültiger Preis erforderlich. Ohne passenden Preis holen Sie bitte zuerst ein Angebot über eine Einkaufsanfrage ein.</DialogDescription></DialogHeader><DialogContent className="max-h-[70vh] space-y-4 overflow-y-auto px-6 py-4">
    <div className="flex flex-wrap items-center gap-3"><Button variant="outline" onClick={() => setPicker(true)}>{lieferant ? `Lieferant: ${lieferant.lieferantenname}` : 'Lieferant wählen'}</Button>{kontakt && <span className="text-sm text-slate-600">Kontakt: {kontakt.name ?? kontakt.email}</span>}{kontakte.length > 0 && <Select aria-label="Bestellkontakt" value={kontaktId} options={kontakte.map(item => ({ value: String(item.id), label: `${item.name ?? item.email}${item.standardBestellung ? ' · Standard' : ''}` }))} onChange={setKontaktId} />}</div>
    {loading ? <p role="status">Verfügbare Bedarfe werden geladen …</p> : <div className="space-y-3">{bedarfe.length === 0 ? <p className="text-sm text-slate-600">Es gibt keine verfügbaren, direkt bestellbaren Artikelbedarfe.</p> : bedarfe.map(need => { const item = drafts[need.id]; const key = need.position.interneReferenz ?? String(need.id); return <article key={need.id} className="rounded-lg border border-slate-200 p-3"><label className="flex items-center gap-2 font-medium"><input aria-label={`Bedarf ${key} auswählen`} type="checkbox" checked={selected.includes(need.id)} onChange={event => setSelected(current => event.target.checked ? [...current, need.id] : current.filter(id => id !== need.id))} />{key} · {need.position.bezeichnung ?? 'Artikelbedarf'}</label><p className="ml-6 text-sm text-slate-600">Noch verfügbar: {(need.mengen.disponierbar ?? 0).toLocaleString('de-DE')} {need.position.basis?.einheit?.toLowerCase()}</p>{selected.includes(need.id) && <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-sm">Menge {key}<input inputMode="decimal" className="mt-1 w-full rounded border border-slate-300 px-3 py-2" value={item.menge} onFocus={event => { if (event.currentTarget.value === '0' || event.currentTarget.value === '0,00') update(need.id, 'menge', ''); }} onChange={event => update(need.id, 'menge', event.target.value)} /></label><label className="text-sm">Preis {key} / {need.position.basis?.einheit?.toLowerCase()}<input inputMode="decimal" aria-label={`Preis ${key}`} className="mt-1 w-full rounded border border-slate-300 px-3 py-2" value={item.preis} onChange={event => update(need.id, 'preis', event.target.value)} /></label><label className="text-sm">Preis bestätigt am {key}<DatePicker aria-label={`Preis bestätigt am ${key}`} max={heute()} value={item.bestaetigtAm} onChange={value => update(need.id, 'bestaetigtAm', value)} /></label><label className="text-sm">Gültig bis {key}<DatePicker aria-label={`Preis gültig bis ${key}`} min={heute()} value={item.gueltigBis} onChange={value => update(need.id, 'gueltigBis', value)} /></label><label className="text-sm sm:col-span-2">Preisquelle {key}<input aria-label={`Preisquelle ${key}`} className="mt-1 w-full rounded border border-slate-300 px-3 py-2" placeholder="z. B. Angebotsnummer oder Lieferantenbeleg" value={item.quelle} onChange={event => update(need.id, 'quelle', event.target.value)} /></label></div>}</article>; })}</div>}
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Liefertermin<DatePicker className="mt-1 w-full" value={liefertermin} onChange={setLiefertermin} /></label><label className="text-sm">Bestätigungsfrist<DatePicker className="mt-1 w-full" value={bestaetigungsfrist} onChange={setBestaetigungsfrist} /></label></div><label className="block text-sm">Zusätzliche Bedingungen<textarea className="mt-1 w-full rounded border border-slate-300 p-2" value={bedingungen} onChange={event => setBedingungen(event.target.value)} /></label>
  </DialogContent><DialogFooter className="border-t border-slate-200 px-6 py-4"><Button variant="outline" onClick={onClose}>Abbrechen</Button><Button disabled={busy || loading || selected.length === 0} onClick={() => void create()}>{busy ? 'Legt Entwurf an …' : 'Direktbestellung als Entwurf anlegen'}</Button></DialogFooter><LieferantSearchModal isOpen={picker} onClose={() => setPicker(false)} onSelect={value => void chooseSupplier(value)} /></Dialog>;
}
