spring.datasource.url=jdbc:mysql://localhost:3307/kalkulationsprogramm_db?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_german2_ci
spring.datasource.username=Marvin
spring.datasource.password=

# RAG deaktivieren (kein Gemini API-Key vorhanden)
ai.rag.enabled=false