#!/usr/bin/env python3
"""Generate the proxy allowlist from MobileApiPolicy; fail closed on unknown syntax."""
import argparse
import json
from pathlib import Path
import re

HERE = Path(__file__).resolve().parent
POLICY = HERE.parents[1] / 'src/main/java/org/example/kalkulationsprogramm/config/MobileApiPolicy.java'
TARGET = HERE / 'mobile-routes.conf'


def render(source: str) -> str:
    id_match = re.search(r'private static final String ID = ("(?:[^"\\]|\\.)*");', source)
    if not id_match:
        raise ValueError('MobileApiPolicy.ID could not be parsed')
    identifier = json.loads(id_match.group(1))
    result = ['# Generated by sync_routes.py from MobileApiPolicy.java. Do not edit.',
              '"~^GET:/zeiterfassung(?:/.*)?$" 1;']
    count = 0
    for line in source.splitlines():
        if not re.match(r'\s*route\("', line):
            continue
        match = re.fullmatch(r'\s*route\("(GET|POST|PUT|PATCH|DELETE)",\s*(.*?)\),?\s*', line)
        if not match:
            raise ValueError('Unsupported route declaration; update this generator explicitly')
        method, expression = match.groups()
        tokens = re.findall(r'"(?:[^"\\]|\\.)*"|\bID\b|\+|\s+', expression)
        if ''.join(tokens) != expression:
            raise ValueError('Unsupported route expression')
        pieces = [token for token in tokens if not token.isspace() and token != '+']
        pattern = ''.join(identifier if token == 'ID' else json.loads(token) for token in pieces)
        re.compile(pattern)
        result.append(json.dumps(f'~^{method}:{pattern}$') + ' 1;')
        count += 1
    if count != source.count('route("') or count == 0:
        raise ValueError('Not all MobileApiPolicy routes were parsed')
    return '\n'.join(result) + '\n'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = render(POLICY.read_text())
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != expected:
            raise SystemExit('Proxy routes differ from MobileApiPolicy. Run sync_routes.py and review the diff.')
        print('Proxy route allowlist matches MobileApiPolicy.')
    else:
        TARGET.write_text(expected)
        print('Generated mobile-routes.conf; review changed public routes before deployment.')


if __name__ == '__main__':
    main()
