import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import { Button } from '../components/ui/button';
import { DetailLayout } from '../components/DetailLayout';
import { PageLayout } from '../components/layout/PageLayout';
import { EinkaufNavigation } from '../features/einkauf/components/EinkaufNavigation';
import { AnfrageLieferanten } from '../features/einkauf/components/AnfrageLieferanten';
import { KommunikationsVerlauf } from '../features/einkauf/components/KommunikationsVerlauf';
import { Select } from '../components/ui/select-custom';
import { DatePicker } from '../components/ui/datepicker';
import { useToast } from '../components/ui/toast';

type KontaktSnapshot = { lieferantId: number; kontaktId: number; lieferantenname: string; email: string; name: string | null; anrede: string | null; eigeneKundennummer: string | null };
type Herkunft = { bedarfId: number; version: number; menge: number };
type Detail = { kopf: { id: number; version: number; paNummer: string; zustaendigId?: number | null; revisionsNummer: number; aktuelleRevisionId: number | null; angezeigteRevisionId: number; historisch: boolean; status: string; antwortfrist?: string; liefertermin?: string; projektIds?: number[]; antworten?: number; lieferantenAnzahl?: number }; positionen: { id: number; snapshot: { bezeichnung: string; interneReferenz?: string; basis?: { menge: number; einheit: string } }; herkuenfte: Herkunft[] }[]; lieferanten: { id: number; lieferantenname: string; status: string; version: number; kontakt?: KontaktSnapshot }[] };
type Revision = { id: number; nummer: number; status: string; antwortfrist?: string | null; liefertermin?: string | null };
type Bedarf = { id: number; version: number; position: { bezeichnung: string }; mengen: { disponierbar: number }; };
type Lieferant = { id: number; lieferantenname: string; kundenNummer?: string };
type Kontakt = { id: number; email: string; name?: string | null; anrede?: string | null; standardAnfrage: boolean; aktiv: boolean };
function NeueAnfrage({ onCreated }: { onCreated: (id: number) => void }) {
 const toast=useToast(); const [bedarfe,setBedarfe]=useState<Bedarf[]>([]); const [lieferanten,setLieferanten]=useState<Lieferant[]>([]); const [ausgewaehlteBedarfe,setAusgewaehlteBedarfe]=useState<number[]>([]); const [ausgewaehlteLieferanten,setAusgewaehlteLieferanten]=useState<number[]>([]); const [kontakte,setKontakte]=useState<Record<number,Kontakt[]>>({}); const [kontaktIds,setKontaktIds]=useState<Record<number,number>>({}); const [antwortfrist,setAntwortfrist]=useState(''); const [liefertermin,setLiefertermin]=useState(''); const [speichert,setSpeichert]=useState(false);
 useEffect(()=>{let aktiv=true; Promise.all([fetch('/api/einkauf/bedarf?page=0&size=100').then(async r=>{if(!r.ok)throw new Error('Bedarf konnte nicht geladen werden.');return await r.json();}),fetch('/api/lieferanten?page=0&size=100').then(async r=>{if(!r.ok)throw new Error('Lieferanten konnten nicht geladen werden.');return await r.json();})]).then(([b,l])=>{if(aktiv){setBedarfe(b.content??[]);setLieferanten(l.lieferanten??l.content??[]);}}).catch(e=>toast.error(e instanceof Error?e.message:'Auswahllisten konnten nicht geladen werden.'));return()=>{aktiv=false;};},[toast]);
 const toggleLieferant=async(id:number)=>{const aktiv=!ausgewaehlteLieferanten.includes(id);setAusgewaehlteLieferanten(old=>aktiv?[...old,id]:old.filter(x=>x!==id));if(aktiv&&!kontakte[id]){try{const r=await fetch(`/api/lieferanten/${id}/einkauf-kontakte`);if(!r.ok)throw new Error('Einkaufskontakte konnten nicht geladen werden.');const items=await r.json() as Kontakt[];setKontakte(old=>({...old,[id]:items.filter(k=>k.aktiv)}));const standard=items.find(k=>k.aktiv&&k.standardAnfrage);if(standard)setKontaktIds(old=>({...old,[id]:standard.id}));}catch(e){toast.error(e instanceof Error?e.message:'Einkaufskontakte konnten nicht geladen werden.');}}};
 const speichern=async()=>{if(!ausgewaehlteBedarfe.length){toast.error('Bitte mindestens eine Position auswählen.');return;}if(ausgewaehlteLieferanten.some(id=>!kontaktIds[id])){toast.error('Bitte für jeden Lieferanten einen Einkaufskontakt auswählen.');return;}if(antwortfrist&&liefertermin&&antwortfrist>liefertermin){toast.error('Die Antwortfrist darf nicht nach dem Liefertermin liegen.');return;}setSpeichert(true);try{const snapshots=ausgewaehlteLieferanten.map(id=>{const lieferant=lieferanten.find(l=>l.id===id)!;const kontakt=kontakte[id].find(k=>k.id===kontaktIds[id])!;return{lieferantId:id,kontaktId:kontakt.id,email:kontakt.email,lieferantenname:lieferant.lieferantenname,name:kontakt.name,anrede:kontakt.anrede,eigeneKundennummer:lieferant.kundenNummer??null};});const r=await fetch('/api/einkauf/anfragen',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({positionen:ausgewaehlteBedarfe.map(id=>{const b=bedarfe.find(x=>x.id===id)!;return{bedarfId:b.id,version:b.version,menge:b.mengen.disponierbar};}),empfaenger:snapshots,antwortfrist:antwortfrist||null,liefertermin:liefertermin||null,zustaendigId:null,idempotenzKey:crypto.randomUUID()})});const d=await r.json();if(!r.ok)throw new Error(d.message||'Anfrage konnte nicht gespeichert werden.');toast.success('Anfrage gespeichert.');onCreated(d.kopf.id);}catch(e){toast.error(e instanceof Error?e.message:'Anfrage konnte nicht gespeichert werden.');}finally{setSpeichert(false);}};
 return <section className="space-y-5 rounded-lg border border-slate-200 bg-white p-5"><div><h2 className="text-lg font-semibold">Neue Anfrage vorbereiten</h2><p className="text-sm text-slate-600">Wählen Sie die offenen Positionen, Einkaufskontakte und Fristen. Gesendet wird erst nach Prüfung der Vorschau.</p></div><fieldset><legend className="mb-2 font-medium">Positionen *</legend>{bedarfe.length?bedarfe.map(b=><label key={b.id} className="flex items-center gap-2 border-t border-slate-100 py-2"><input type="checkbox" checked={ausgewaehlteBedarfe.includes(b.id)} onChange={e=>setAusgewaehlteBedarfe(old=>e.target.checked?[...old,b.id]:old.filter(x=>x!==b.id))}/>{b.position.bezeichnung} · {b.mengen.disponierbar} offen</label>):<p className="text-sm text-slate-600">Kein offener Bedarf vorhanden.</p>}</fieldset><fieldset><legend className="mb-2 font-medium">Lieferanten und Empfänger *</legend>{lieferanten.map(l=><div key={l.id} className="border-t border-slate-100 py-2"><label className="flex items-center gap-2"><input type="checkbox" checked={ausgewaehlteLieferanten.includes(l.id)} onChange={()=>void toggleLieferant(l.id)}/>{l.lieferantenname}</label>{ausgewaehlteLieferanten.includes(l.id)&&<Select aria-label={`Einkaufskontakt ${l.lieferantenname}`} className="mt-2" value={String(kontaktIds[l.id]??'')} placeholder="Einkaufskontakt wählen" options={(kontakte[l.id]??[]).map(k=>({value:String(k.id),label:`${k.name||k.email} · ${k.email}`}))} onChange={value=>setKontaktIds(old=>({...old,[l.id]:Number(value)}))}/>}</div>)}</fieldset><div className="grid gap-4 sm:grid-cols-2"><div><label className="mb-1 block text-sm font-medium" htmlFor="antwortfrist">Antwortfrist</label><DatePicker id="antwortfrist" aria-label="Antwortfrist" value={antwortfrist} onChange={setAntwortfrist}/></div><div><label className="mb-1 block text-sm font-medium" htmlFor="liefertermin">Gewünschter Liefertermin</label><DatePicker id="liefertermin" aria-label="Liefertermin" value={liefertermin} onChange={setLiefertermin}/></div></div><Button disabled={speichert} onClick={()=>void speichern()}>{speichert?'Speichert …':'Anfrage speichern und Vorschau öffnen'}</Button></section>;
}
function RevisionEditor({detail,onCancel,onSaved}:{detail:Detail;onCancel:()=>void;onSaved:(detail:Detail)=>void}) {
 const toast=useToast();const [antwortfrist,setAntwortfrist]=useState(detail.kopf.antwortfrist??'');const [liefertermin,setLiefertermin]=useState(detail.kopf.liefertermin??'');const [mengen,setMengen]=useState<Record<number,string>>(()=>Object.fromEntries(detail.positionen.flatMap(p=>p.herkuenfte.map(h=>[h.bedarfId,String(h.menge)]))));const [empfaenger,setEmpfaenger]=useState(()=>detail.lieferanten.flatMap(l=>l.kontakt?[l.kontakt]:[]));const [busy,setBusy]=useState(false);
 const speichern=async()=>{const positionen: Herkunft[]=[];for(const p of detail.positionen)for(const h of p.herkuenfte){const raw=mengen[h.bedarfId]?.trim().replace(',','.');const menge=Number(raw);if(!raw||!Number.isFinite(menge)||menge<=0){toast.error(`Bitte für „${p.snapshot.bezeichnung}“ eine gültige Menge größer als 0 eingeben.`);return;}positionen.push({...h,menge});}if(!empfaenger.length){toast.error('Bitte mindestens einen Lieferantenkontakt übernehmen.');return;}if(antwortfrist&&liefertermin&&antwortfrist>liefertermin){toast.error('Die Antwortfrist darf nicht nach dem Liefertermin liegen.');return;}setBusy(true);try{const r=await fetch(`/api/einkauf/anfragen/${detail.kopf.id}/revisionen`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:detail.kopf.version,inhalt:{positionen,empfaenger,antwortfrist:antwortfrist||null,liefertermin:liefertermin||null,zustaendigId:detail.kopf.zustaendigId??null,idempotenzKey:crypto.randomUUID()}})});const d=await r.json();if(!r.ok)throw new Error(d.message||'Neue Fassung konnte nicht gespeichert werden.');toast.success('Neue Fassung gespeichert.');onSaved(d as Detail);}catch(e){toast.error(e instanceof Error?e.message:'Neue Fassung konnte nicht gespeichert werden.');}finally{setBusy(false);}};
 return <section className="space-y-4 rounded-lg border border-rose-200 bg-rose-50/40 p-4"><div><h2 className="font-semibold">Neue Anfragefassung</h2><p className="text-sm text-slate-600">Mengen und Fristen anpassen. Die bisherige Fassung bleibt im Verlauf erhalten.</p></div><fieldset><legend className="mb-2 font-medium">Positionen und Teilmengen *</legend>{detail.positionen.map(p=><div key={p.id} className="border-t border-slate-200 py-2"><p>{p.snapshot.bezeichnung}</p>{p.herkuenfte.map(h=><label key={h.bedarfId} className="mt-1 flex items-center gap-2 text-sm">Menge <input aria-label={`Menge ${p.snapshot.bezeichnung}`} className="w-28 rounded border border-slate-300 bg-white px-2 py-1" inputMode="decimal" value={mengen[h.bedarfId]??''} onFocus={e=>{if(Number(e.currentTarget.value.replace(',','.'))===0)e.currentTarget.value='';}} onChange={e=>setMengen(old=>({...old,[h.bedarfId]:e.target.value}))}/><span>{p.snapshot.basis?.einheit}</span></label>)}</div>)}</fieldset><div className="grid gap-3 sm:grid-cols-2"><div><label className="mb-1 block text-sm font-medium" htmlFor="revision-antwortfrist">Antwortfrist</label><DatePicker id="revision-antwortfrist" value={antwortfrist} onChange={setAntwortfrist}/></div><div><label className="mb-1 block text-sm font-medium" htmlFor="revision-liefertermin">Gewünschter Liefertermin</label><DatePicker id="revision-liefertermin" value={liefertermin} onChange={setLiefertermin}/></div></div><div><p className="mb-2 font-medium">Lieferanten und Empfänger *</p>{empfaenger.map((k,i)=><label key={`${k.lieferantId}-${k.kontaktId}`} className="flex items-center gap-2 border-t border-slate-200 py-2 text-sm"><input type="checkbox" checked onChange={()=>setEmpfaenger(old=>old.filter((_,n)=>n!==i))}/>{k.lieferantenname} · {k.name||k.email} · {k.email}</label>)}</div><div className="flex gap-2"><Button disabled={busy} onClick={()=>void speichern()}>{busy?'Speichert …':'Fassung speichern'}</Button><Button variant="outline" onClick={onCancel}>Abbrechen</Button></div></section>;
}
export default function EinkaufsanfrageDetail() {
 const { id }=useParams(); const navigate=useNavigate(); const [detail,setDetail]=useState<Detail|null>(null); const [revisionen,setRevisionen]=useState<Revision[]>([]); const [fehler,setFehler]=useState(''); const [erstellt,setErstellt]=useState(false); const neu=id==='neu';
 useEffect(()=>{if(neu)return;let aktiv=true;const laden=async()=>{try{const [dr,rr]=await Promise.all([fetch(`/api/einkauf/anfragen/${encodeURIComponent(id??'')}`),fetch(`/api/einkauf/anfragen/${encodeURIComponent(id??'')}/revisionen`)]);if(!dr.ok||!rr.ok)throw new Error('Anfrage konnte nicht geladen werden.');const [d,r]=await Promise.all([dr.json() as Promise<Detail>,rr.json() as Promise<Revision[]>]);if(aktiv){setDetail(d);setRevisionen(r);}}catch(e){if(aktiv)setFehler(e instanceof Error?e.message:'Anfrage konnte nicht geladen werden.');}};void laden();return()=>{aktiv=false;};},[id,neu]);
 const revisionWaehlen=async(value:string)=>{if(!id)return;const revisionId=Number(value);setFehler('');try{const r=await fetch(`/api/einkauf/anfragen/${id}/revisionen/${revisionId}`);if(!r.ok)throw new Error('Anfragefassung konnte nicht geladen werden.');setDetail(await r.json() as Detail);}catch(e){setFehler(e instanceof Error?e.message:'Anfragefassung konnte nicht geladen werden.');}};
 return <PageLayout ribbonCategory="Einkauf" title={neu?'NEUE EINKAUFSANFRAGE':detail?.kopf.paNummer??'EINKAUFSANFRAGE'} subtitle={neu?'Positionen und Empfänger für eine Anfrage zusammenstellen.':'Positionen, Lieferanten und Nachrichtenverlauf ansehen.'} actions={<Link to="/einkaufsanfragen"><Button variant="outline" size="sm"><ArrowLeft className="mr-2 h-4 w-4"/>Zur Übersicht</Button></Link>}><div className="space-y-5"><EinkaufNavigation active="anfragen"/>{neu?<NeueAnfrage onCreated={created=>navigate(`/einkaufsanfragen/${created}`,{replace:true})}/>:fehler?<p role="alert" className="text-rose-700">{fehler}</p>:!detail?<p role="status">Anfrage wird geladen …</p>:<DetailLayout header={<div className="rounded-lg border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-600">{detail.kopf.status} · Revision {detail.kopf.revisionsNummer}{detail.kopf.historisch?' · frühere Fassung (nur Lesen)':''}</p><div className="flex items-center gap-2"><Select aria-label="Anfragefassung" value={String(detail.kopf.angezeigteRevisionId)} options={revisionen.map(r=>({value:String(r.id),label:`Fassung ${r.nummer} · ${r.status}`}))} onChange={v=>void revisionWaehlen(v)}/>{!detail.kopf.historisch&&<Button size="sm" variant="outline" onClick={()=>setErstellt(true)}>Neue Revision</Button>}</div></div><p>Antwortfrist: {detail.kopf.antwortfrist??'Keine Frist'} · Liefertermin: {detail.kopf.liefertermin??'Kein Termin'}</p>{detail.kopf.historisch&&<p className="mt-1 text-sm text-amber-800">Diese Fassung ist schreibgeschützt. Frühere Antworten bleiben dieser Version zugeordnet.</p>}</div>} mainContent={<div className="space-y-5">{erstellt&&<RevisionEditor detail={detail} onCancel={()=>setErstellt(false)} onSaved={d=>{setDetail(d);setErstellt(false);void fetch(`/api/einkauf/anfragen/${d.kopf.id}/revisionen`).then(r=>r.json()).then(setRevisionen);}}/>}<section className="rounded-lg border border-slate-200 bg-white p-4"><h2 className="font-semibold">Positionen · Revision {detail.kopf.revisionsNummer}</h2>{detail.positionen.map(p=><p key={p.id} className="border-t border-slate-100 py-3">{p.snapshot.bezeichnung} <span className="text-slate-500">{p.herkuenfte.map(h=>`${h.menge} ${p.snapshot.basis?.einheit??''}`).join(', ')}</span></p>)}</section><AnfrageLieferanten anfrageId={detail.kopf.id} revisionId={detail.kopf.angezeigteRevisionId} lieferanten={detail.lieferanten} historisch={detail.kopf.historisch}/><KommunikationsVerlauf typ="ANFRAGE" vorgangId={detail.kopf.id}/></div>} sideContent={<section className="rounded-lg border border-slate-200 bg-white p-4"><h2 className="font-semibold">Fristen und Verlauf</h2><p>Antwortfrist: {detail.kopf.antwortfrist??'Keine Frist'}</p><p>Liefertermin: {detail.kopf.liefertermin??'Kein Termin'}</p><p className="mt-3 text-sm text-slate-600">Der Verlauf zeigt Nachrichten mit der dazugehörigen Revision.</p></section>}/>}</div></PageLayout>;
}
