-- Add RECHNUNG and GUTSCHRIFT to all dokumenttyp ENUM columns

ALTER TABLE geschaeftsdokument
    MODIFY COLUMN dokumenttyp_enum
        ENUM('ANGEBOT','AUFTRAGSBESTAETIGUNG','RECHNUNG','TEILRECHNUNG','ABSCHLAGSRECHNUNG',
             'SCHLUSSRECHNUNG','ZAHLUNGSERINNERUNG','ERSTE_MAHNUNG','ZWEITE_MAHNUNG',
             'STORNORECHNUNG','GUTSCHRIFT') NOT NULL;

ALTER TABLE formular_template_assignment
    MODIFY COLUMN dokumenttyp_enum
        ENUM('ANGEBOT','AUFTRAGSBESTAETIGUNG','RECHNUNG','TEILRECHNUNG','ABSCHLAGSRECHNUNG',
             'SCHLUSSRECHNUNG','ZAHLUNGSERINNERUNG','ERSTE_MAHNUNG','ZWEITE_MAHNUNG',
             'STORNORECHNUNG','GUTSCHRIFT') NOT NULL;

ALTER TABLE textbaustein_dokumenttyp_enum
    MODIFY COLUMN dokumenttyp
        ENUM('ANGEBOT','AUFTRAGSBESTAETIGUNG','RECHNUNG','TEILRECHNUNG','ABSCHLAGSRECHNUNG',
             'SCHLUSSRECHNUNG','ZAHLUNGSERINNERUNG','ERSTE_MAHNUNG','ZWEITE_MAHNUNG',
             'STORNORECHNUNG','GUTSCHRIFT') NULL;
