CREATE TABLE IF NOT EXISTS einkauf_mailantwort_vorschau (
    freigabe_token CHAR(64) NOT NULL,
    email_id BIGINT NOT NULL,
    konto_id VARCHAR(16) NOT NULL,
    einkauf_typ VARCHAR(24) NOT NULL,
    vorgang_id BIGINT NOT NULL,
    beteiligung_id BIGINT NULL,
    revision_id BIGINT NULL,
    source_message_id VARCHAR(512) NOT NULL,
    in_reply_to VARCHAR(1000) NOT NULL,
    references_header JSON NOT NULL,
    empfaenger VARCHAR(1000) NOT NULL,
    subject VARCHAR(998) NOT NULL,
    html_body LONGTEXT NOT NULL,
    anlagen JSON NOT NULL,
    inhalt_sha256 CHAR(64) NOT NULL,
    versand_id BIGINT NULL,
    angenommen_am TIMESTAMP(6) NULL,
    erstellt_am TIMESTAMP(6) NOT NULL,
    gueltig_bis TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (freigabe_token),
    CONSTRAINT fk_einkauf_mailantwort_email FOREIGN KEY (email_id) REFERENCES email(id),
    CONSTRAINT fk_einkauf_mailantwort_versand FOREIGN KEY (versand_id) REFERENCES einkauf_versandauftrag(id),
    CONSTRAINT uk_einkauf_mailantwort_versand UNIQUE (versand_id),
    INDEX idx_einkauf_mailantwort_bindung (email_id, konto_id, einkauf_typ, vorgang_id),
    INDEX idx_einkauf_mailantwort_ablauf (gueltig_bis)
);
